apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: games-store-service
    version: 1.0.0-SNAPSHOT-129
  name: games-store-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-store-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: games-store-service
        version: 1.0.0-SNAPSHOT-129
    spec:
      containers:
      - image: quay.io/zgrinber/games-store-service:1.0.0-SNAPSHOT-129
        name: games-store-service
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE
          value: 'true'
        - name: QUARKUS_SWAGGER_UI_ENABLE
          value: 'true'
        - name: QUARKUS_MONGODB_CONNECTION_STRING
          value: mongodb://mongodb-for-game-store:27017
        - name: BUILD_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['version']
